apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: dev
  labels:
    app: engine
spec:
  selector:
    app: engine
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
  type: ClusterIP
