apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: dev
  labels:
    app: manager
spec:
  selector:
    app: manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
