{
 "title": "Azure / Insights / PostgreSQL / Flexible Server Monitoring",
 "description": "Azure monitor dashboard for Azure Database for PostgreSQL Flexible Server health including server health, resource usage (cpu, memory, iops, storage), connections, throughput, latency etc.",
 "tags": [ "Azure-managed" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "am_ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "Microsoft.DBforPostgreSQL/flexibleServers"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "res",
    "label": "Resource",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://sqltune.files.wordpress.com/2023/07/azure-database-for-postgresql-bigger.png\"/>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 19, "x": 1, "y": 0 },
   "options": {
    "content": "# Azure Database for PostgreSQL Flexible Server - Monitoring Dashboard\r\n#### - Each metric is emitted at a 1-minute interval and has up to 93 days of history.\r\n#### - For complete list of metrics, refer [Azure PostgreSQL Monitoring Metrics](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-monitoring)"
   }
  },
  {
   "title": "Database State",
   "type": "stat",
   "description": "Indicates if the database is up or not",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "is_db_alive",
      "metricNamespace": "$ns",
      "region": "",
      "resources": [
       {
        "metricNamespace": "$ns",
        "region": "",
        "resourceGroup": "$rg",
        "resourceName": "$res",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU Usage (Avg)",
   "type": "gauge",
   "description": "Percentage of CPU in use",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "resourceGroup": "$rg",
        "resourceName": "$res",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory Usage (Avg)",
   "type": "gauge",
   "description": "Percentage of memory in use",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage Usage Percent (Avg)",
   "type": "gauge",
   "description": "Percent of storage space that's used. The storage that's used by the service can include database files, transaction logs, and server logs",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage Used/Free",
   "type": "bargauge",
   "description": "Used and Free storage. The storage that's used by the service can include the database files, transaction logs, and the server logs.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "storage_used",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "storage_free",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Provisioned Storage",
   "type": "stat",
   "description": "The storage you provision is the amount of storage capacity available to your Azure Database for PostgreSQL server. The storage is used for the database files, temporary files, transaction logs, and the PostgreSQL server logs",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "T-Log Storage Used (Bytes)",
   "type": "stat",
   "description": "Amount of storage space that's used by the transaction logs",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "txlogs_storage_used",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Read-Replica",
   "type": "stat",
   "description": "Read Replica Configured",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "physical_replication_delay_in_bytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Number of connections to your server",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "active_connections",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Succeeded Connections",
   "type": "stat",
   "description": "Number of succeeded connections",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "connections_succeeded",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "description": "Number of total transactions that executed in this database.",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "xact_total",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "description": "Number of data disk I/O read operations per second.",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "read_iops",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "description": "Number of data disk I/O write operations per second",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "write_iops",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "description": "Bytes read per second from disk",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "read_throughput",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "description": "Bytes written to disk per second",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "read_throughput",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Network In (Bytes)",
   "type": "stat",
   "description": "Amount of incoming network traffic",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "network_bytes_ingress",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Network Out (Bytes)",
   "type": "stat",
   "description": "Amount of outgoing network traffic",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "network_bytes_egress",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 17 },
   "options": {
    "content": "#### **NOTE**: While metrics are stored for 93 days, you can only query (in the Metrics tile) for a maximum of 30 days' worth of data on any single chart. If you see a blank chart or your chart displays only part of metric data, verify that the difference between start and end dates in the time picker doesn't exceed the 30-day interval. After you've selected a 30-day interval, you can pan the chart to view the full retention window."
   }
  },
  { "title": "Resource consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU / Memory",
   "type": "timeseries",
   "description": "Percentage of CPU in use",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "cpu_percent",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "memory_percent",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Transactions per second (Preview)",
   "type": "timeseries",
   "description": "Number of transactions executed within a second.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 28 },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Total Transactions by database (Top n)",
   "type": "piechart",
   "description": "Number of total transactions that executed in this database (by database)",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "DatabaseName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "xact_total",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Transaction Log Storage Used (Bytes)",
   "type": "timeseries",
   "description": "Amount of storage space that's used by the transaction logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 37 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "txlogs_storage_used",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage Used (Bytes)",
   "type": "timeseries",
   "description": "Amount of storage space that's used. The storage that's used by the service can include the database files, transaction logs, and the server logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "storage_used",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage Free (Bytes)",
   "type": "timeseries",
   "description": "Amount of storage space that's available",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "storage_free",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "timeseries",
   "description": "Number of active, failed and succeeded connections to your server.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 54 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "active_connections",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "connections_failed",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_succeeded",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Connections Configured",
   "type": "stat",
   "description": "Max Connections represents the configured value for the _max_connections_ server parameter. This metric is pooled every 30 minutes.",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "max_connections",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT30M",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Read/Write throughput",
   "type": "timeseries",
   "description": "Bytes Read / Written to disk per second.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "read_throughput",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "write_throughput",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "description": "Number of data disk IO read/write operations per second.",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 63 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "read_iops",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
      "metricName": "write_iops",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Autovacuum Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 72 },
     "options": {
      "content": "#### **NOTE**: Autovacuum metrics are emitted at a 30-minute interval. To enable these metrics, set the server parameter `metrics.autovacuum_diagnostics` to ON."
     }
    },
    {
     "title": "Dead Tuples",
     "type": "timeseries",
     "description": "Estimated number of dead rows for user-only tables in this database",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 74 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "n_dead_tup_user_tables",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "PT30M",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Live Tuples",
     "type": "timeseries",
     "description": "Estimated number of live rows for user-only tables in this database.",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 74 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "n_live_tup_user_tables",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Bloat Percent (Preview)",
     "type": "timeseries",
     "description": "Estimated bloat percentage for user only tables.",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 83 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "bloat_percent",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "PgBouncer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 73 },
     "options": {
      "content": "#### **NOTE**: PgBouncer  metrics are emitted at a 30-minute interval. For PgBouncer metrics to work, both the server parameters `pgbouncer.enabled` and `metrics.pgbouncer_diagnostics` must be enabled."
     }
    },
    {
     "title": "Number of connection pools",
     "type": "timeseries",
     "description": "Total number of connection pools",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 75 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "num_pools",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Active client connections",
     "type": "timeseries",
     "description": "Connections from clients that are associated with an Azure Database for PostgreSQL connection",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 75 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "client_connections_active",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Active server connections",
     "type": "timeseries",
     "description": "Connections to Azure Database for PostgreSQL that are in use by a client connection",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 75 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "server_connections_active",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Total pooled connections",
     "type": "timeseries",
     "description": "Current number of pooled connections",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 82 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "total_pooled_connections",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Waiting client connections",
     "type": "timeseries",
     "description": "Connections from clients that are waiting for an Azure Database for PostgreSQL connection to service them",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 82 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "client_connections_waiting",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Idle server connections",
     "type": "timeseries",
     "description": "Connections to Azure Database for PostgreSQL that are idle and ready to service a new client connection",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 82 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "server_connections_idle",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Enhanced Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
     "options": {
      "content": "#### **NOTE**: Enhanced metrics are emitted at a 1-minute interval. To enable these metrics, set the server parameter `metrics.collector_database_activity` to ON."
     }
    },
    {
     "title": "Sessions by State",
     "type": "timeseries",
     "description": "Overall state of the back ends",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "State",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "sessions_by_state",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Sessions By WaitEventType",
     "type": "timeseries",
     "description": "Sessions by the type of event for which the back end is waiting",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "WaitEventType",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "sessions_by_wait_event_type",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Session Stats",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 92 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "longest_transaction_time_sec",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "longest_query_time_sec",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "oldest_backend_time_sec",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Tuples Inserted",
     "type": "timeseries",
     "description": "Number of rows that were inserted by queries in this database",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 102 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "tup_inserted",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Transactions Committed",
     "type": "timeseries",
     "description": "Number of transactions in this database that have been committed",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 102 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "blks_read",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Transactions Rolled back",
     "type": "timeseries",
     "description": "Number of transactions in this database that have been rolled back",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 102 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "xact_rollback",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Disk Blocks Hit",
     "type": "timeseries",
     "description": "Number of times disk blocks were found already in the buffer cache, so that a read wasn't necessary",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 111 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "blks_hit",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Disk Blocks Read",
     "type": "timeseries",
     "description": "Number of disk blocks that were read in this database",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 111 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "DatabaseName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "blks_read",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Physical Replication Lag - On Primary",
     "type": "stat",
     "description": "Maximum lag across all asynchronous physical replication slots",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "physical_replication_delay_in_bytes",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Read Replica Lag - On Secondry",
     "type": "stat",
     "description": "Read replica lag in seconds",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "physical_replication_delay_in_seconds",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Historical Metrics (last 30 days)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": " Database availability (Last 30 days)",
     "type": "timeseries",
     "description": "Indicates if the database is up or not in last 30 days",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 92 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "is_db_alive",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Backup Storage Used (last 30 days)",
     "type": "timeseries",
     "description": "Amount of backup storage used. This metric represents the sum of storage that's consumed by all the full backups, differential backups, and log backups that are retained based on the backup retention period that's set for the server. The frequency of the backups is service managed. For geo-redundant storage, backup storage usage is twice the usage for locally redundant storage",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{metric}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "dimensions": [],
        "metricDefinition": "Microsoft.DBforPostgreSQL/flexibleServers",
        "metricName": "backup_storage_used",
        "metricNamespace": "$ns",
        "resources": [
         { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}