import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  chatWrapper: {
    maxWidth: "50%",
    margin: "30px auto",
    display: "flex",
    flexDirection: "column",
    fontFamily: "Arial, sans-serif",
    border: "1px solid #ddd",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 6px 20px rgba(0,0,0,0.1)",
    height: "70vh",
  },
  chatTitle: {
    background: "#cce6ff",
    padding: "18px",
    fontSize: "24px",
    fontWeight: "bold",
    textAlign: "center",
    color: "#3c3c3c",
  },
  chatContainer: {
    flex: 1,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    overflowY: "auto",
    height: "60vh",
    background: "#f9f9f9",
  },
  avatarImg: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
  },
  msgBubble: {
    color: "#333",
    padding: "12px 16px",
    borderRadius: "16px",
    maxWidth: "65%",
    wordWrap: "break-word",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "left",
  },
  msgBubbleAI: {
    background: "#e2e2e2",
    color: "#333",
    padding: "12px 16px",
    borderRadius: "16px",
    maxWidth: "65%",
    fontSize: "16px",
    textAlign: "left",
  },
  msgWrapper: {
    display: "flex",
    alignItems: "flex-end",
    gap: "10px",
  },
  inputAndBtnWrapper: {
    display: "flex",
    borderTop: "1px solid #ddd",
    background: "#F0F0F0FF",
    padding: "15px",
    gap: "10px",
  },
  input: {
    flex: 1,
    padding: "12px",
    fontSize: "16px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    background: "#ffffff",
  },
  sendBtn: {
    color: "white",
    fontSize: "16px",
    borderRadius: "8px",
    border: "none",
    padding: "0 20px",
  },
});
