{
 "title": "AI dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "👥Number of users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by (namespace) (\r\n sum by (namespace, user) (\r\n count_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"}\r\n |= \"Chat request\" |= \" finished in \"\r\n | regexp \"userId (?P<uid>[0-9A-Fa-f-]{32,36})\"\r\n | label_format user=\"{{.uid}}\"\r\n )[$__range])\r\n )\r\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "🗪 Unique chats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\r\n (\r\n sum by (namespace, chat) (\r\n count_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} \r\n |= \"Chat request\" |= \" finished in \"\r\n | regexp \"chatId (?P<cid>[0-9A-Fa-f-]{36})\"\r\n | label_format chat=\"{{.cid}}\"\r\n )[1h])\r\n ) > 0\r\n )\r\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "⌛Duration of call",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n sum by (namespace, kind) (\r\n avg_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} |= \" finished in \"\r\n | regexp \"finished in (?P<ms>[0-9]+)\\\\s*ms\"\r\n | label_format kind=\"overall\"\r\n | unwrap ms\r\n )[$__auto])\r\n )\r\n) / 1000\r\n",
     "legendFormat": "Finish ({{namespace}})"
    },
    {
     "direction": "backward",
     "expr": "(\r\n sum by (namespace, kind) (\r\n avg_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} |= \"afterChatServiseTime\"\r\n | regexp \"afterChatServiseTime (?P<ms>[0-9]+)\\\\s*ms\"\r\n | label_format kind=\"afterChatService\"\r\n | unwrap ms\r\n )[$__auto])\r\n )\r\n) / 1000",
     "legendFormat": "Call LLM ({{namespace}})"
    },
    {
     "direction": "backward",
     "expr": "(\r\n sum by (namespace, kind) (\r\n avg_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} |= \"addOrCheckChatNameTime\"\r\n | regexp \"addOrCheckChatNameTime (?P<ms>[0-9]+)\\\\s*ms\"\r\n | label_format kind=\"chatName\"\r\n | unwrap ms\r\n )[$__auto])\r\n )\r\n) / 1000\r\n",
     "legendFormat": "check ChatName ({{namespace}})"
    },
    {
     "direction": "backward",
     "expr": "(\r\n sum by (namespace, kind) (\r\n avg_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} |= \"addOrCheckSystemPromptTime\"\r\n | regexp \"addOrCheckSystemPromptTime (?P<ms>[0-9]+)\\\\s*ms\"\r\n | label_format kind=\"systemPrompt\"\r\n | unwrap ms\r\n )[$__auto])\r\n )\r\n) / 1000\r\n",
     "legendFormat": "Check System Prompt ({{namespace}})"
    },
    {
     "direction": "backward",
     "expr": "(\r\n sum by (namespace, kind) (\r\n avg_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} |= \"addOrCheckSystemPromptTime\"\r\n | regexp \"addOrCheckSystemPromptTime (?P<ms>[0-9]+)\\\\s*ms\"\r\n | label_format kind=\"systemPrompt\"\r\n | unwrap ms\r\n )[$__auto])\r\n )\r\n) / 1000",
     "legendFormat": "Get history ({{namespace}})"
    }
   ]
  },
  {
   "title": "⚒️Plugins used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace, plugin) (\r\n count_over_time((\r\n {app=\"engine\", namespace=~\"${namespace:regex}\"} \r\n |= \"Plugin \" |= \" executed\"\r\n | regexp \"Plugin (?P<plugin>[A-Za-z0-9_.-]+) executed\"\r\n | label_format plugin=\"{{.plugin}}\"\r\n )[$__auto])\r\n)",
     "legendFormat": "🕰️TimePlugin {{namespace}}"
    }
   ]
  },
  {
   "title": "📞Call to chatService",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace, kind) (\r\n  count_over_time((\r\n    {app=\"engine\", namespace=~\"${namespace:regex}\"} \r\n    |= \"processed successfully\"\r\n    | label_format kind=\"success\"\r\n  )[$__auto])\r\n)\r\n",
     "legendFormat": "✅success {{namespace}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (namespace, kind) (\r\n  count_over_time((\r\n    {app=\"engine\", namespace=~\"${namespace:regex}\"} \r\n    |= \"failed:\"\r\n    | label_format kind=\"fail\"\r\n  )[$__auto])\r\n)",
     "legendFormat": "❌fail{{namespace}}"
    }
   ]
  },
  {
   "title": "📞All calls to LLM",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "All calls",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalCalls",
      "metricNamespace": "microsoft.cognitiveservices/accounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.CognitiveServices/accounts",
        "region": "francecentral",
        "resourceGroup": "azure-open-ai-playground",
        "resourceName": "france-teachin-open-ai",
        "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
       }
      ],
      "timeGrain": "PT1H",
      "top": ""
     },
     "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Success",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulCalls",
      "metricNamespace": "microsoft.cognitiveservices/accounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.CognitiveServices/accounts",
        "region": "francecentral",
        "resourceGroup": "azure-open-ai-playground",
        "resourceName": "france-teachin-open-ai",
        "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
       }
      ],
      "timeGrain": "PT1H"
     },
     "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Error",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalErrors",
      "metricNamespace": "microsoft.cognitiveservices/accounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.CognitiveServices/accounts",
        "region": "francecentral",
        "resourceGroup": "azure-open-ai-playground",
        "resourceName": "france-teachin-open-ai",
        "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
       }
      ],
      "timeGrain": "PT1H"
     },
     "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
    },
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "🪙All tokens",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Input",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ModelDeploymentName", "filters": [ "gpt-4.1-mini" ], "operator": "eq" },
       { "dimension": "ApiName", "filters": [ "OpenAI" ], "operator": "eq" }
      ],
      "metricName": "ProcessedPromptTokens",
      "metricNamespace": "microsoft.cognitiveservices/accounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.CognitiveServices/accounts",
        "region": "francecentral",
        "resourceGroup": "azure-open-ai-playground",
        "resourceName": "france-teachin-open-ai",
        "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
       }
      ],
      "timeGrain": "PT1H",
      "top": ""
     },
     "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Output tokens",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "GeneratedTokens",
      "metricNamespace": "microsoft.cognitiveservices/accounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.CognitiveServices/accounts",
        "region": "francecentral",
        "resourceGroup": "azure-open-ai-playground",
        "resourceName": "france-teachin-open-ai",
        "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
       }
      ],
      "timeGrain": "PT1H",
      "top": ""
     },
     "subscription": "90ea4c2f-1eee-4ec9-927d-ed24c563003e"
    }
   ]
  }
 ]
}