import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  authPageBackground: {
    minHeight: "100vh",
    width: "100%",
    boxSizing: "border-box",
    padding: "1rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "fixed",
    overflowY: "auto",
  },
  authPageHeader: {
    marginTop: "6vh",
    textAlign: "center",
    paddingBottom: "1rem",
  },
  authPageTitle: {
    margin: 0,
    padding: 0,
    fontSize: "1.75rem",
    fontWeight: 600,
    color: "white",
    textShadow: "0 2px 6px rgba(0,0,0,0.3)",
    lineHeight: 1.2,
  },
  authPageSubtitle: {
    padding: 0,
    fontSize: "1.1rem",
    fontWeight: 500,
    color: "#23437a",
    textAlign: "center",
  },
  authPageContent: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginBottom: "6vh",
  },
  authPageContainer: {
    width: "100%",
    maxWidth: 400,
    border: "1px solid #e0e0e0",
    background: "white",
    margin: "0 auto 0",
    padding: "1.5rem 2.5rem 2.5rem 2.5rem",
    borderRadius: 12,
    boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  authPageTabs: {
    display: "flex",
    gap: "0.5rem",
    position: "relative",
    background: "white",
    borderRadius: 8,
  },
  authPageTab: {
    flex: 1,
    border: "1px solid #23437a",
    cursor: "pointer",
    padding: "0.75rem 0",
    textAlign: "center",
    fontWeight: 500,
    zIndex: 1,
    color: "#23437a",
    background: "transparent",
    transition: "color 200ms, background 200ms",
    "&.active": {
      color: "white",
      background: "#23437a",
    },
    "&.active:hover": {
      background: "#232e7a",
    },
  },
  authPageForm: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  authPageInput: {
    boxSizing: "border-box",
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: 6,
    border: "1px solid #cbd2d9",
    background: "#f7f9fa",
    color: "#000",
    fontSize: "1rem",
    transition: "border-color 200ms, background 200ms",
    "&:focus": {
      outline: "none",
      borderColor: "#23437a",
    },
    "&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus": {
      WebkitTextFillColor: "#000 !important",
      WebkitBoxShadow: "0 0 0px 1000px #f7f9fa inset !important",
      boxShadow: "0 0 0px 1000px #f7f9fa inset !important",
    },
  },
  authPageError: {
    color: "red",
    fontSize: "0.85rem",
    minHeight: "1.125rem",
  },
  authPageSubmit: {
    padding: "0.75rem",
    background: "#23437a",
    color: "white",
    border: "none",
    cursor: "pointer",
    borderRadius: 6,
    fontWeight: 500,
    fontSize: "1rem",
    transition: "background 200ms",
    "&:hover:not(:disabled)": {
      background: "#232e7a",
    },
    "&:disabled": {
      background: "#7aaedc",
      cursor: "not-allowed",
    },
  },
});
