import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  listContainer: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 2px 4px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)",
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderRadius: 12,
    padding: "1.25rem 1.15rem 1.5rem",
    position: "relative",
    transition: "box-shadow .25s ease, transform .25s ease",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    "@supports (height: 100dvh)": {
      height: "calc(100dvh - 46px)",
    },
  },
  sectionTitle: {
    margin: "0 0 0.85rem",
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 0.3,
    color: "#1a202c",
    textAlign: "center",
  },
  tableArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  tableShell: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    background: "#fff",
  },
  rowsScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
    scrollbarGutter: "stable",
  },
  table: {
    tableLayout: "fixed",
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    "& .MuiTableCell-head": {
      textAlign: "inherit",
      background: "#f8fafc",
      fontWeight: 600,
      color: "#1f2937",
      whiteSpace: "nowrap",
      position: "sticky",
      top: 0,
      zIndex: 1,
      boxSizing: "border-box",
      verticalAlign: "middle",
    },
    "& .MuiTableBody-root .MuiTableCell-root": {
      textAlign: "center",
      whiteSpace: "nowrap",
      verticalAlign: "top",
      boxSizing: "border-box",
    },
    "@media (max-width: 600px)": {
      "& .MuiTableCell-root": {
        padding: "6px 8px",
        fontSize: 13,
      },
    },
  },
  tableWide: {
    "@media (max-width: 600px)": {
      minWidth: 700,
    },
  },
  colStudent: {
    width: "72%",
    "@media (max-width: 900px)": { width: "65%" },
    "@media (max-width: 600px)": { width: "58%" },
  },
  colMetrics: {
    width: "28%",
    "@media (max-width: 900px)": { width: "35%" },
    "@media (max-width: 600px)": { width: "42%" },
  },
  cap: { textTransform: "capitalize" },
  ellipsis: {
    display: "block",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rateWrapper: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
  },
  rateBarWrap: {
    width: 140,
    "@media (max-width: 600px)": { width: 90 },
  },
  rateBar: {
    height: 8,
    borderRadius: 6,
    "& .MuiLinearProgress-bar": { borderRadius: 6 },
  },
  rateText: {
    fontSize: 12,
    color: "#475569",
  },
  paginationBar: {
    padding: "4px 12px",
    background: "#fff",
  },
  groupCell: {
    padding: 0,
    borderBottom: "none",
  },
  groupAccordion: {
    borderRadius: 10,
    border: "1px solid #e5e7eb",
    overflow: "hidden",
    margin: "6px 0",
    boxShadow: "0 2px 6px rgba(0,0,0,0.04)",
    "&::before": { display: "none" },
  },
  groupSummary: {
    padding: "10px 12px",
    background: "#fafafa",
    "& .MuiAccordionSummary-content": {
      margin: 0,
      width: "100%",
    },
  },
  groupDetails: {
    padding: "10px 12px 12px",
    background: "#fff",
  },
  summaryBar: {
    display: "grid",
    alignItems: "center",
    gap: 12,
    width: "100%",
    minHeight: 32,
    gridTemplateColumns: "72% 28%",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "65% 35%",
    },
    "@media (max-width: 600px)": {
      gridTemplateColumns: "58% 42%",
    },
  },
  summaryLeft: {
    minWidth: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 600,
    color: "#0f172a",
  },
  studentId: {
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  summaryRight: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    rowGap: 8,
    flexWrap: "nowrap",
    justifySelf: "end",
    overflowX: "auto",
    overflowY: "hidden",
    whiteSpace: "nowrap",
    "& strong": { fontWeight: 700 },
    scrollbarGutter: "stable",
    "-webkit-overflow-scrolling": "touch",
    paddingRight: 10,
  },
  metric: {
    padding: "4px 8px",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    background: "#fff",
    fontSize: 13,
    flex: "0 0 auto",
  },
  ratePill: {
    padding: "4px 10px",
    borderRadius: 999,
    background: "#eef2ff",
    border: "1px solid #c7d2fe",
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
    flex: "0 0 auto",
  },
  innerTable: {
    border: "1px solid #eef2f7",
    borderRadius: 8,
    overflow: "hidden",
    tableLayout: "fixed",
    width: "100%",
    "& .MuiTableCell-head": {
      background: "#f9fafb",
      textAlign: "center",
      boxSizing: "border-box",
      verticalAlign: "middle",
    },
    "& .MuiTableBody-root .MuiTableCell-root": {
      textAlign: "center",
      boxSizing: "border-box",
      verticalAlign: "middle",
    },
  },
  colInnerGameType: { width: "22%" },
  colInnerDifficulty: { width: "18%" },
  colInnerAttempts: { width: "15%" },
  colInnerSuccesses: { width: "15%" },
  colInnerFailures: { width: "15%" },
  colInnerRate: { width: "15%" },
  "@media (max-width: 700px)": {
    colInnerGameType: { width: "220px" },
    colInnerDifficulty: { width: "180px" },
    colInnerAttempts: { width: "140px" },
    colInnerSuccesses: { width: "140px" },
    colInnerFailures: { width: "140px" },
    colInnerRate: { width: "140px" },
  },
  innerRow: {
    "&:hover": {
      background: "#fafafa",
    },
  },
  colGameType: { textAlign: "center" },
  colDifficulty: { textAlign: "center" },
  colAttempts: { textAlign: "center" },
  colRate: { textAlign: "center" },
});
