import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  pageWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    backgroundColor: "#f5f5f5",
    padding: "20px",
    boxSizing: "border-box",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100vh - 40px)",
    minHeight: "400px",
    width: "100%",
    maxWidth: "800px",
    border: "1px solid #e1e5e9",
    borderRadius: "12px",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    position: "relative",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  content: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "12px",
    minHeight: 0,
    overflow: "auto",
    paddingBottom: "40px",
  },
  exerciseArea: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    gap: "10px",
    minHeight: 0,
  },
  audioSection: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    gap: "12px",
    minHeight: 0,
  },
  typingInput: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "16px",
    border: "2px solid #e1e5e9",
    borderRadius: "12px",
    backgroundColor: "#ffffff",
  },
  typingInputField: {
    width: "100%",
    padding: "16px",
    border: "2px solid #e1e5e9",
    borderRadius: "8px",
    fontSize: "18px",
    backgroundColor: "#ffffff",
    color: "#333333",
    direction: "rtl",
    textAlign: "right",
    boxSizing: "border-box",
    "&:focus": { outline: "none", borderColor: "#007bff" },
    "&::placeholder": { color: "#6c757d" },
    fontFamily: "'Times New Roman', 'David Libre', 'Frank Ruehl CLM', serif",
    fontFeatureSettings: "'kern' 1, 'liga' 1, 'clig' 1",
    textRendering: "optimizeLegibility",
  },
  typingSubmitButton: {
    alignSelf: "flex-end",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#28a745",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    "&:hover": { backgroundColor: "#218838" },
    "&:disabled": { backgroundColor: "#6c757d", cursor: "not-allowed" },
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  backButtonWrapper: {
    marginTop: "20px",
    textAlign: "center",
  },
  "@media (max-width: 768px)": {
    pageWrapper: {
      padding: "10px",
      minHeight: "100vh",
    },
    container: {
      height: "calc(100vh - 40px)",
      maxWidth: "100%",
      margin: "20px",
    },
  },
});
