// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Accessor.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accessor.DB.Migrations
{
    [DbContext(typeof(AccessorDbContext))]
    [Migration("20251120081729_SeedAchievements")]
    partial class SeedAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accessor.Models.Achievements.AchievementModel", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feature");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("AchievementId");

                    b.HasIndex("Feature");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements", (string)null);

                    b.HasData(
                        new
                        {
                            AchievementId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first word card",
                            Feature = "WordCards",
                            IsActive = true,
                            Key = "word_cards_first",
                            Name = "First Steps",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 3 word cards",
                            Feature = "WordCards",
                            IsActive = true,
                            Key = "word_cards_3",
                            Name = "Word Explorer",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 5 word cards",
                            Feature = "WordCards",
                            IsActive = true,
                            Key = "word_cards_5",
                            Name = "Word Master",
                            TargetCount = 5,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first typing practice",
                            Feature = "TypingPractice",
                            IsActive = true,
                            Key = "typing_first",
                            Name = "Keyboard Warrior",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 3 typing practices",
                            Feature = "TypingPractice",
                            IsActive = true,
                            Key = "typing_3",
                            Name = "Speed Typer",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 5 typing practices",
                            Feature = "TypingPractice",
                            IsActive = true,
                            Key = "typing_5",
                            Name = "Typing Champion",
                            TargetCount = 5,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first speaking practice",
                            Feature = "SpeakingPractice",
                            IsActive = true,
                            Key = "speaking_first",
                            Name = "Breaking the Ice",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 3 speaking practices",
                            Feature = "SpeakingPractice",
                            IsActive = true,
                            Key = "speaking_3",
                            Name = "Confident Speaker",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 5 speaking practices",
                            Feature = "SpeakingPractice",
                            IsActive = true,
                            Key = "speaking_5",
                            Name = "Voice Master",
                            TargetCount = 5,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first word order game",
                            Feature = "WordOrder",
                            IsActive = true,
                            Key = "word_order_first",
                            Name = "Sentence Builder",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 3 word order games",
                            Feature = "WordOrder",
                            IsActive = true,
                            Key = "word_order_3",
                            Name = "Grammar Guru",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 5 word order games",
                            Feature = "WordOrder",
                            IsActive = true,
                            Key = "word_order_5",
                            Name = "Syntax Master",
                            TargetCount = 5,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice your first mistake",
                            Feature = "PracticeMistakes",
                            IsActive = true,
                            Key = "mistakes_first",
                            Name = "Learning from Errors",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice 3 mistakes",
                            Feature = "PracticeMistakes",
                            IsActive = true,
                            Key = "mistakes_3",
                            Name = "Mistake Master",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice 5 mistakes",
                            Feature = "PracticeMistakes",
                            IsActive = true,
                            Key = "mistakes_5",
                            Name = "Error Eliminator",
                            TargetCount = 5,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("60000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first word cards challenge",
                            Feature = "WordCardsChallenge",
                            IsActive = true,
                            Key = "challenge_first",
                            Name = "Challenge Accepted",
                            TargetCount = 1,
                            Type = "Milestone"
                        },
                        new
                        {
                            AchievementId = new Guid("60000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 3 word cards challenges",
                            Feature = "WordCardsChallenge",
                            IsActive = true,
                            Key = "challenge_3",
                            Name = "Challenge Champion",
                            TargetCount = 3,
                            Type = "Count"
                        },
                        new
                        {
                            AchievementId = new Guid("60000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 5 word cards challenges",
                            Feature = "WordCardsChallenge",
                            IsActive = true,
                            Key = "challenge_5",
                            Name = "Ultimate Challenger",
                            TargetCount = 5,
                            Type = "Count"
                        });
                });

            modelBuilder.Entity("Accessor.Models.Achievements.UserAchievementModel", b =>
                {
                    b.Property<Guid>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_achievement_id");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Achievements.UserProgressModel", b =>
                {
                    b.Property<Guid>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_progress_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserProgressId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Feature")
                        .IsUnique();

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.ChatHistorySnapshot", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ThreadId");

                    b.ToTable("ChatHistorySnapshots", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Classes.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ClassId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Classes_Name_CI");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Classes.ClassMembership", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId", "UserId", "Role");

                    b.HasIndex("ClassId", "Role", "UserId");

                    b.HasIndex("UserId", "Role", "ClassId");

                    b.ToTable("ClassMemberships", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.GameConfiguration.UserGameConfig", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Nikud")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfSentences")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GameName");

                    b.ToTable("UserGameConfigs", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Games.GameAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("numeric");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<List<string>>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<List<string>>("GivenAnswer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExerciseId", "AttemptNumber");

                    b.HasIndex("StudentId", "Status");

                    b.HasIndex("StudentId", "GameType", "Difficulty");

                    b.ToTable("GameAttempts", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Meetings.MeetingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("GroupCallId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupCallId");

                    b.HasIndex("StartTimeUtc");

                    b.HasIndex("Status");

                    b.ToTable("Meetings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Meetings_DurationMinutes", "\"DurationMinutes\" >= 1 AND \"DurationMinutes\" <= 1440");
                        });
                });

            modelBuilder.Entity("Accessor.Models.Prompts.PromptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PromptKey");

                    b.HasIndex("PromptKey", "Version");

                    b.ToTable("Prompts", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.RefreshSessionsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceFingerprintHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_fingerprint_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("NOW() + INTERVAL '60 days'");

                    b.Property<IPAddress>("IP")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceFingerprintHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("RevokedAt");

                    b.HasIndex("UserId");

                    b.ToTable("refreshSessions", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "payload");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Accessor.Models.Users.TeacherStudent", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("TeacherId", "StudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherStudents", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Users.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcsUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AvatarUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HebrewLevelValue")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PreferredLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("AcsUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.WordCards.WordCardModel", b =>
                {
                    b.Property<Guid>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("english");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Hebrew")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hebrew");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_learned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CardId");

                    b.HasIndex("UserId", "IsLearned");

                    b.ToTable("WordCards", (string)null);
                });

            modelBuilder.Entity("Accessor.Models.Achievements.UserAchievementModel", b =>
                {
                    b.HasOne("Accessor.Models.Achievements.AchievementModel", null)
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accessor.Models.Classes.ClassMembership", b =>
                {
                    b.HasOne("Accessor.Models.Classes.Class", "Class")
                        .WithMany("Memberships")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accessor.Models.Users.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accessor.Models.Classes.Class", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
