{{- /*
Creates two ExternalSecret objects that read from Azure Key Vault (via an
existing ClusterSecretStore) and write Kubernetes Secrets in the target namespace.

Requires:
  - ClusterSecretStore named .Values.global.keyvault.storeName (default: azure-keyvault-backend)
  - The 6 Key Vault secrets already exist with the names from step #1
*/ -}}

{{- $ns := include "app.namespace" . -}}
{{- $store := .Values.global.keyvault.storeName | default "azure-keyvault-backend" -}}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manager-appsettings
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $store }}
  target:
    name: {{ .Values.manager.secrets.jwt.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
{{- range .Values.manager.secrets.jwt.data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .remote }}
{{- end }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: engine-appsettings
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $store }}
  target:
    name: {{ .Values.engine.secrets.app.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
{{- range .Values.engine.secrets.app.data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .remote }}
{{- end }}
