apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proxy
  namespace: db-proxy
  labels:
    app: postgres-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-proxy
  template:
    metadata:
      labels:
        app: postgres-proxy
    spec:
      containers:
      - name: postgres-proxy
        image: alpine/socat:latest
        imagePullPolicy: IfNotPresent
        command: ["socat"]
        args:
          - "TCP-LISTEN:5432,fork,reuseaddr"
          - "TCP:${POSTGRES_PRIVATE_FQDN}:5432"
        env:
        - name: PROXY_TARGET
          value: "${POSTGRES_PRIVATE_FQDN}:5432"
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proxy-svc
  namespace: db-proxy
  labels:
    app: postgres-proxy
spec:
  selector:
    app: postgres-proxy
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
