apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: accessor-queue-in
  namespace: {{ include "app.namespace" . }}
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: namespaceName
      value: "{{ .Values.global.servicebus.namespace }}"
    - name: queueName
      value: "accessor-queue"
    - name: direction
      value: input
    - name: disableEntityManagement
      value: "true"
    - name: azureClientId
      value: "{{ .Values.global.servicebus.clientId }}"
scopes:
  - {{ .Values.accessor.dapr.appId  | default .Values.accessor.name  | quote }}