apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ default "dapr-config" .Values.dapr.configuration.name | lower | quote }}
  namespace: {{ include "app.namespace" . }}
spec:
  tracing:
    samplingRate: "1"
