apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Values.global.dapr.configName | default "daprConfig" }}
  namespace: {{ include "app.namespace" . }}
spec:
  tracing:
    samplingRate: "1"
