apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ include "app.namespace" . | quote }}
  annotations:
    dapr.io/component-init-timeout: "120s"
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "{{ .Values.redis.host }}:6380"
    - name: enableTLS
      value: "true"
    - name: useEntraID
      value: "true"
    - name: azureClientId
      value: "{{ .Values.global.azure.clientId }}"
    - name: dialTimeout
      value: '{{ default "30s" .Values.dapr.stateStore.redis.options.dialTimeout }}'
    - name: readTimeout
      value: '{{ default "30s" .Values.dapr.stateStore.redis.options.readTimeout }}'
    - name: writeTimeout
      value: '{{ default "30s" .Values.dapr.stateStore.redis.options.writeTimeout }}'
    - name: poolTimeout
      value: '{{ default "30s" .Values.dapr.stateStore.redis.options.poolTimeout }}'
    - name: idleTimeout
      value: '{{ default "300s" .Values.dapr.stateStore.redis.options.idleTimeout }}'
    - name: maxConnAge
      value: '{{ default "30m" .Values.dapr.stateStore.redis.options.maxConnAge }}'
    - name: redisDB
      value: '{{ .Values.dapr.stateStore.redis.redisDB }}'
scopes:
  - {{ include "app.appIdFor" (list $ .Values.accessor.name) | quote }}
  - {{ include "app.appIdFor" (list $ .Values.manager.name)  | quote }}
  - {{ include "app.appIdFor" (list $ .Values.engine.name)   | quote }}
