import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
	homePageWrapper: {
		display: 'flex',
		flexDirection: 'column',
		gap: '16px',
		maxWidth: '1200px',
		margin: '0 auto',
	},
	columnsWrapper: {
		display: 'flex',
		gap: '5%',
		flexWrap: 'wrap',
		justifyContent: 'center',
	},
	column: {
		display: 'flex',
		flexDirection: 'column',
		gap: '20px',
		minWidth: 200,
	},
	button: {
		background: '#59BEDFFF',
		color: 'white',
		padding: [10, 20],
		border: 'none',
		borderRadius: 15,
		cursor: 'pointer',
		'&:hover': {
			background: '#1B81A6FF',
		},
	},
	chatDaPageWrapper: {
		display: 'flex',
		height: 'calc(100vh - 4rem)',
	},
	chatDaChatWrapper: {
		flex: 1,
		display: 'flex',
		marginTop: '5%',
	},
	fullScreenAvatarDaPage: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		margin: 0,
		padding: 0,
		overflow: 'hidden',
	},
	authPageContainer: {
		maxWidth: 400,
		border: '1px solid #e0e0e0',
		background: 'white',
		margin: '10vh auto',
		padding: '2.5rem',
		borderRadius: 12,
		boxShadow: '0 8px 24px rgba(0,0,0,0.08)',
	},
	authPageTabs: {
		display: 'flex',
		gap: '0.5rem',
		position: 'relative',
		background: 'white',
		borderRadius: 8,
		marginBottom: '2rem',
	},
	authPageTab: {
		flex: 1,
		border: '1px solid #1976d2',
		cursor: 'pointer',
		padding: '0.75rem 0',
		textAlign: 'center',
		fontWeight: 500,
		zIndex: 1,
		color: '#1976d2',
		background: 'transparent',
		transition: 'color 200ms, background 200ms',
		'&.active': {
			color: 'white',
			background: '#1976d2',
		},
	},
	authPageForm: {
		display: 'flex',
		flexDirection: 'column',
		gap: '0.75rem',
	},
	authPageInput: {
		boxSizing: 'border-box',
		width: '100%',
		padding: '0.75rem 1rem',
		borderRadius: 6,
		border: '1px solid #cbd2d9',
		background: '#f7f9fa',
		fontSize: '1rem',
		transition: 'border-color 200ms',
		'&:focus': {
			outline: 'none',
			borderColor: '#1976d2',
			background: 'white',
		},
	},
	authPageError: {
		color: 'red',
		fontSize: '0.85rem',
		minHeight: '1.125rem',
	},
	authPageSubmit: {
		padding: '0.75rem',
		background: '#1976d2',
		color: 'white',
		border: 'none',
		cursor: 'pointer',
		borderRadius: 6,
		fontWeight: 500,
		fontSize: '1rem',
		transition: 'background 200ms',
		'&:hover:not(:disabled)': {
			background: '#155a9c',
		},
		'&:disabled': {
			background: '#7aaedc',
			cursor: 'not-allowed',
		},
	},
});
