apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: devops-logs
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prom-stack-kube-prometheus-prometheus.monitoring.svc:9090
        uid: prometheus
        isDefault: false