# Prometheus configuration with Dapr metrics scraping
prometheus:
  prometheusSpec:
    # Resource settings
    retention: "8h"
    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "512Mi"
    scrapeInterval: "60s"
    evaluationInterval: "60s"
    
    # Additional scrape configs for Dapr metrics
    additionalScrapeConfigs:
      # Dapr sidecar metrics (port 9090)
      - job_name: 'dapr-sidecar-metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Only scrape pods with dapr.io/enabled annotation
          - source_labels: [__meta_kubernetes_pod_annotation_dapr_io_enabled]
            action: keep
            regex: true
          # Only scrape the dapr sidecar container (daprd)
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: daprd
          # Set the metrics path to /
          - target_label: __metrics_path__
            replacement: /
          # Set the port to 9090 (Dapr metrics port)
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:9090
          # Add useful labels
          - source_labels: [__meta_kubernetes_pod_annotation_dapr_io_app_id]
            target_label: dapr_app_id
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
        scrape_interval: 300s # memory saver: update interval to 5 minutes
        scrape_timeout: 10s
        metric_relabel_configs: # memory saver: drop noisy series
          # Keep only essential Dapr metrics
          - source_labels: [__name__]
            regex: "dapr_http_server_request_duration_seconds.*|dapr_grpc_io_server_duration_seconds.*|dapr_runtime_state_calls_total|dapr_runtime_state_duration_seconds.*|dapr_runtime_pubsub_messages_published_total|dapr_runtime_pubsub_messages_received_total|dapr_runtime_actor_calls_total|dapr_runtime_actor_duration_seconds.*"
            action: keep
          # Drop everything else
          - source_labels: [__name__]
            regex: ".*"
            action: drop
        
      # Dapr placement service metrics
      - job_name: 'dapr-placement'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['dapr-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: dapr-placement-server
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:9090
          - target_label: __metrics_path__
            replacement: /
        scrape_interval: 60s
        
      # Dapr operator metrics
      - job_name: 'dapr-operator'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['dapr-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: dapr-operator
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:9090
          - target_label: __metrics_path__
            replacement: /
        scrape_interval: 60s

# Disable Grafana (we use separate Grafana installation)
grafana:
  enabled: false

# Keep AlertManager enabled
alertmanager:
  enabled: true
