import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  container: {
    display: "flex",
    flexDirection: "column",
    padding: 24,
    background: "linear-gradient(135deg, #e0f7fa, #fce4ec)",
    minHeight: "100vh",
    alignItems: "center",
    justifyContent: "start",
    gap: 24,
    fontFamily: '"Inter", sans-serif',
  },
  inputGroup: {
    display: "flex",
    gap: 16,
    width: "100%",
    maxWidth: 600,
  },
  select: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    background: "rgba(255,255,255,0.6)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.4)",
    boxShadow:
      "4px 4px 12px rgba(0,0,0,0.05), -4px -4px 12px rgba(255,255,255,0.7)",
    fontSize: "1rem",
    color: "#333",
    "&:hover": { transform: "scale(1.02)", transition: "0.2s" },
  },
  searchGroup: {
    display: "flex",
    flex: 1,
    gap: 8,
  },
  input: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    border: "none",
    background: "rgba(255,255,255,0.6)",
    backdropFilter: "blur(8px)",
    boxShadow:
      "4px 4px 12px rgba(0,0,0,0.05), -4px -4px 12px rgba(255,255,255,0.7)",
    fontSize: "1rem",
    color: "#333",
    "&:hover": { transform: "scale(1.02)", transition: "0.2s" },
    "&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus": {
      WebkitTextFillColor: "#000 !important",
      WebkitBoxShadow: "0 0 0px 1000px #f7f9fa inset !important",
      boxShadow: "0 0 0px 1000px #f7f9fa inset !important",
    },
  },
  button: {
    padding: "12px 20px",
    borderRadius: 12,
    border: "none",
    background: "#007aff",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow:
      "4px 4px 12px rgba(0,0,0,0.1), -4px -4px 12px rgba(255,255,255,0.5)",
    "&:hover": {
      background: "#005bb5",
      transform: "scale(1.05)",
      transition: "0.2s",
    },
  },
  messageContainer: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  loading: {
    fontStyle: "italic",
    fontSize: "1.125rem",
    color: "#555",
  },
  error: {
    color: "#d32f2f",
    fontSize: "1rem",
    textAlign: "center",
  },
  heading: {
    fontSize: "2rem",
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: "#333",
  },
  weatherContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  iconContainer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    transform: "translateZ(0)",
    transition: "transform 0.2s",
    "&:hover": { transform: "translateZ(8px)" },
    background: "#fff",
    borderRadius: "50%",
    padding: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,0.15)",
  },
  temp: {
    fontSize: "2.5rem",
    fontWeight: 700,
    color: "#333",
  },
  description: {
    fontSize: "1.25rem",
    textTransform: "capitalize",
    color: "#555",
  },
  icon: {
    width: 75,
    height: 75,
  },
  stats: {
    fontSize: "1rem",
    color: "#555",
    lineHeight: 1.6,
    textAlign: "center",
    maxWidth: 500,
  },
});
