import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
    container: {
        display: "flex",
        flexDirection: "column",
        maxHeight: "90%",
        minHeight: "200px",
        width: "100%",
        maxWidth: "800px",
        border: "1px solid #e1e5e9",
        borderRadius: "12px",
        backgroundColor: "#ffffff",
        overflow: "hidden",
        position: "relative",
    },
    header: {
        flexShrink: 0,
        padding: "12px 16px",
        borderBottom: "1px solid #e1e5e9",
        backgroundColor: "#f8f9fa",
        textAlign: "center",
    },
    title: { margin: 0, fontSize: "19px", fontWeight: "600", color: "#333333" },
    subtitle: { margin: 0, fontSize: "11px", color: "#6c757d" },
    content: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        padding: "12px",
        minHeight: 0,
        overflow: "hidden",
    },

    exerciseArea: { display: "flex", flexDirection: "column", flex: 1, gap: "10px", minHeight: 0 },
    exerciseHeader: {
        flexShrink: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        paddingBottom: "12px",
        borderBottom: "1px solid #e1e5e9",
    },
    exerciseTitle: { fontSize: "14px", fontWeight: "600", color: "#333333", margin: 0 },
    levelBadge: {
        padding: "4px 12px",
        borderRadius: "16px",
        fontSize: "12px",
        fontWeight: "600",
        textTransform: "uppercase",
    },
    levelBadgeEasy: { backgroundColor: "#d4edda", color: "#155724" },
    levelBadgeMedium: { backgroundColor: "#fff3cd", color: "#856404" },
    levelBadgeHard: { backgroundColor: "#f8d7da", color: "#721c24" },
    backButton: {
        padding: "8px 16px",
        border: "1px solid #e1e5e9",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
        cursor: "pointer",
        fontSize: "14px",
        color: "#6c757d",
        "&:hover": { borderColor: "#007bff", color: "#007bff" },
    },

    audioSection: { display: "flex", flexDirection: "column", flex: 1, gap: "12px", minHeight: 0 },
    errorContainer: {
        padding: "12px 16px",
        backgroundColor: "#fee",
        border: "1px solid #fcc",
        borderRadius: "8px",
        color: "#c33",
        fontSize: "14px",
        marginBottom: "16px",
    },

    typingInput: {
        display: "flex",
        flexDirection: "column",
        gap: "16px",
        padding: "16px",
        border: "2px solid #e1e5e9",
        borderRadius: "12px",
        backgroundColor: "#ffffff",
    },
    typingInputField: {
        width: "100%",
        padding: "16px",
        border: "2px solid #e1e5e9",
        borderRadius: "8px",
        fontSize: "18px",
        backgroundColor: "#ffffff",
        color: "#333333",
        direction: "rtl",
        textAlign: "right",
        boxSizing: "border-box",
        "&:focus": { outline: "none", borderColor: "#007bff" },
        "&::placeholder": { color: "#6c757d" },
    },
    typingSubmitButton: {
        alignSelf: "flex-end",
        padding: "12px 24px",
        border: "none",
        borderRadius: "8px",
        backgroundColor: "#28a745",
        color: "#ffffff",
        fontSize: "16px",
        fontWeight: "600",
        cursor: "pointer",
        "&:hover": { backgroundColor: "#218838" },
        "&:disabled": { backgroundColor: "#6c757d", cursor: "not-allowed" },
    },

    loadingOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(255, 255, 255, 0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10,
    },
    loadingSpinner: {
        width: "24px",
        height: "24px",
        border: "2px solid #e1e5e9",
        borderTop: "2px solid #007bff",
        borderRadius: "50%",
        animation: "$spin 1s linear infinite",
    },
    "@keyframes spin": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },

    // Mobile responsive
    "@media (max-width: 768px)": {
        container: { height: "calc(100vh - 40px)", maxWidth: "100%", margin: "20px" },
    },
});