import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
    audioControls: {
        flexShrink: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "12px",
        padding: "16px",
        border: "2px solid #e1e5e9",
        borderRadius: "12px",
        backgroundColor: "#f8f9fa",
    },
    audioInfo: { display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" },
    audioIcon: { fontSize: "32px" },
    audioText: { fontSize: "16px", color: "#333333", fontWeight: "500" },
    audioButtons: { display: "flex", gap: "12px", flexWrap: "wrap", justifyContent: "center" },
    playButton: {
        padding: "12px 24px",
        border: "none",
        borderRadius: "8px",
        backgroundColor: "#007bff",
        color: "#ffffff",
        fontSize: "16px",
        fontWeight: "600",
        cursor: "pointer",
        "&:hover": { backgroundColor: "#0056b3" },
        "&:disabled": { backgroundColor: "#6c757d", cursor: "not-allowed" },
    },
    replayButton: {
        padding: "12px 24px",
        border: "2px solid #007bff",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
        color: "#007bff",
        fontSize: "16px",
        fontWeight: "600",
        cursor: "pointer",
        "&:hover": { backgroundColor: "#007bff", color: "#ffffff" },
        "&:disabled": { borderColor: "#6c757d", color: "#6c757d", cursor: "not-allowed" },
    },
    audioError: {
        padding: "16px",
        backgroundColor: "#fee",
        border: "1px solid #fcc",
        borderRadius: "8px",
        textAlign: "center",
    },
    audioErrorText: { fontSize: "14px", color: "#c33", fontWeight: "500" },
    audioRetryButton: {
        padding: "8px 16px",
        border: "1px solid #c33",
        borderRadius: "6px",
        backgroundColor: "#ffffff",
        color: "#c33",
        cursor: "pointer",
        "&:hover": { backgroundColor: "#c33", color: "#ffffff" },
    },
    loadingSpinner: {
        width: "16px",
        height: "16px",
        border: "2px solid #ffffff",
        borderTop: "2px solid transparent",
        borderRadius: "50%",
        animation: "$spin 1s linear infinite",
        marginRight: "8px",
    },
    "@keyframes spin": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },

    "@media (max-width: 768px)": {
        audioButtons: { flexDirection: "column", width: "100%" },
        playButton: { width: "100%", justifyContent: "center" },
        replayButton: { width: "100%", justifyContent: "center" },
    },
});
