import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  creationContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
    background: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.08)",
    border: "1px solid #e0e0e0",
    padding: "1.5rem 2rem",
    height: "fit-content",
    "@media (min-width: 700px)": {
      minWidth: "350px",
      maxWidth: "400px",
    },
  },
  sectionTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "#2c3e50",
    marginBottom: "1rem",
    borderBottom: "2px solid #3498db",
    paddingBottom: "0.5rem",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#34495e",
    "& input, & textarea": {
      padding: "0.75rem",
      border: "1px solid #bdc3c7",
      borderRadius: "8px",
      fontSize: "1rem",
      backgroundColor: "#fff",
      color: "#222",
      transition: "all 0.3s ease",
      "&:focus": {
        outline: "none",
        borderColor: "#3498db",
        boxShadow: "0 0 0 3px rgba(52,152,219,0.1)",
      },
      "&:disabled": {
        backgroundColor: "#f8f9fa",
        color: "#6c757d",
        cursor: "not-allowed",
      },
    },
    "& textarea": {
      resize: "vertical",
      minHeight: "100px",
      fontFamily: "inherit",
    },
  },
  error: {
    color: "#e74c3c",
    fontSize: "0.8rem",
    minHeight: "1rem",
    display: "flex",
    alignItems: "center",
  },
  statusLabel: {
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#6c757d",
    marginRight: "0.5rem",
  },
  statusValue: {
    fontSize: "0.9rem",
    fontWeight: 600,
    textTransform: "capitalize",
  },
  statusConnected: {
    color: "#28a745",
  },
  statusDisconnected: {
    color: "#dc3545",
  },
  buttonGroup: {
    display: "flex",
    gap: "0.75rem",
    marginTop: "1rem",
  },
  submitButton: {
    flex: 1,
    padding: "0.875rem 1.5rem",
    backgroundColor: "#3498db",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover:not(:disabled)": {
      backgroundColor: "#2980b9",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(52,152,219,0.3)",
    },
    "&:disabled": {
      backgroundColor: "#95a5a6",
      cursor: "not-allowed",
      transform: "none",
      boxShadow: "none",
    },
  },
  cancelButton: {
    flex: 1,
    padding: "0.875rem 1.5rem",
    backgroundColor: "#95a5a6",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: "#7f8c8d",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(149,165,166,0.3)",
    },
  },
  createNewButton: {
    flex: 1,
    padding: "0.875rem 1.5rem",
    backgroundColor: "#27ae60",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: "#229954",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(39,174,96,0.3)",
    },
  },
});
