apiVersion: 1
groups:
  - name: AKS Nodes
    interval: 1m
    rules:
      - uid: node-notready
        title: "AKS Node NotReady"
        datasource: Prometheus
        condition: "kube_node_status_condition{condition='Ready',status='false'} > 0"
        for: 5m
        annotations:
          summary: "One or more nodes are NotReady"
        labels:
          severity: critical
        notifications:
          - teams-webhook

  - name: AKS Pods
    interval: 1m
    rules:
      - uid: pod-crashloop
        title: "Pod CrashLoopBackOff (stage/dev only)"
        datasource: Prometheus
        condition: "kube_pod_container_status_restarts_total{namespace=~'stage|dev'} > 0"
        for: 5m
        annotations:
          summary: "Pod in CrashLoopBackOff"
        labels:
          severity: warning
        notifications:
          - teams-webhook

  - name: Frontend Availability
    interval: 1m
    rules:
      - uid: frontend-errors
        title: "Frontend High 5xx Errors"
        datasource: Azure Monitor
        condition: "requests_failed_total > 10"
        for: 5m
        annotations:
          summary: "High rate of 5xx errors on frontend"
        labels:
          severity: critical
        notifications:
          - teams-webhook

  - name: Static Web App
    interval: 5m
    rules:
      - uid: staticwebapp-errors
        title: "Static Web App Errors"
        datasource: Azure Monitor
        condition: "requests_failed_total{app='static-webapp'} > 5"
        for: 5m
        annotations:
          summary: "Static Web App error spike"
        labels:
          severity: critical
        notifications:
          - teams-webhook

  - name: Cost Management
    interval: 1h
    rules:
      - uid: budget-over
        title: "Azure Budget Threshold Reached"
        datasource: Azure Monitor
        condition: "budget_actual > 0.9 * budget_limit"
        for: 0m
        annotations:
          summary: "Budget threshold exceeded"
        labels:
          severity: warning
        notifications:
          - teams-webhook