apiVersion: 1
groups:
  - name: AKS Nodes
    folder: Infrastructure
    interval: 1m
    rules:
      - uid: node-notready
        title: "AKS Node NotReady"
        condition: A
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: 'kube_node_status_condition{condition="Ready",status="false"}'
              refId: A
              intervalMs: 1000
              maxDataPoints: 43200
            reducer: "max"
        for: 5m
        annotations:
          summary: "One or more nodes are NotReady"
        labels:
          severity: critical

  - name: AKS Pods
    folder: Infrastructure
    interval: 1m
    rules:
      - uid: pod-crashloop
        title: "Pod CrashLoopBackOff (stage/dev only)"
        condition: A
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: 'kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace=~"stage|dev"}'
              refId: A
              intervalMs: 1000
              maxDataPoints: 43200
        for: 5m
        annotations:
          summary: "Pod in CrashLoopBackOff: {{ $labels.pod }}"
        labels:
          severity: warning
