{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: engine-scaledobject
  namespace: {{ include "app.namespace" . }}
spec:
  scaleTargetRef:
    name: {{ .Values.engine.name }}
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 2     # More responsive (was 5)
  cooldownPeriod: 300  # 5 minutes before scaling down
  triggers:
    - type: kubernetes-workload
      metadata:
        podSelector: 'io.kompose.service=manager'
        value: "1"
{{- end }}