{{- if .Values.keda.enabled }}
# ConfigMap to store KEDA HTTP Add-on timeout configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-http-interceptor-timeouts
  namespace: {{ include "app.namespace" . }}
data:
  # KEDA HTTP Interceptor timeout values for scale-to-zero reliability
  KEDA_HTTP_CONNECT_TIMEOUT: "30s"
  KEDA_HTTP_KEEP_ALIVE: "30s"
  KEDA_RESPONSE_HEADER_TIMEOUT: "300s"
  KEDA_HTTP_RESPONSE_TIMEOUT: "300s"
  KEDA_HTTP_REQUEST_TIMEOUT: "300s"
  # Additional performance settings
  KEDA_HTTP_IDLE_CONN_TIMEOUT: "90s"
  KEDA_HTTP_TLS_HANDSHAKE_TIMEOUT: "10s"
  KEDA_HTTP_MAX_IDLE_CONNS: "100"
{{- end }}