{{- if .Values.keda.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keda-interceptor-{{ include "app.namespace" . }}
  namespace: {{ include "app.namespace" . }}
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}