apiVersion: v1
kind: Service
metadata:
  name: keda-interceptor
  namespace: keda
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: keda-add-ons-http-interceptor