{{- if .Values.keda.enabled }}
# Job to patch KEDA HTTP interceptor with proper timeouts for scale-to-zero
apiVersion: batch/v1
kind: Job
metadata:
  name: keda-interceptor-timeout-patch-{{ .Release.Revision }}
  namespace: {{ include "app.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ printf "%s-serviceaccount" .Release.Namespace }}
      restartPolicy: Never
      containers:
      - name: keda-patcher
        image: rancher/kubectl:v1.28.0
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Applying KEDA HTTP interceptor timeout patches..."
          
          # Apply the exact same patch command that works manually
          kubectl patch deployment keda-add-ons-http-interceptor -n keda --type='json' --patch='[{"op": "replace", "path": "/spec/template/spec/containers/0/env/3/value", "value": "30s"},{"op": "replace", "path": "/spec/template/spec/containers/0/env/5/value", "value": "30s"}]'
          
          # Wait for rollout to complete
          kubectl rollout status deployment/keda-add-ons-http-interceptor -n keda --timeout=60s
          
          echo "KEDA timeout patches applied successfully!"
{{- end }}