import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
    feedbackSection: {
        display: "flex",
        flexDirection: "column",
        gap: "12px",
        padding: "16px",
        border: "2px solid #e1e5e9",
        borderRadius: "12px",
        backgroundColor: "#ffffff",
        flex: 1,
        minHeight: 0,
        overflow: "auto",
    },
    feedbackHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        paddingBottom: "12px",
        borderBottom: "1px solid #e1e5e9",
    },
    feedbackTitle: { fontSize: "18px", fontWeight: "600", color: "#333333", margin: 0 },
    accuracyBadge: { padding: "6px 12px", borderRadius: "16px", fontSize: "14px", fontWeight: "600" },
    accuracyHigh: { backgroundColor: "#d4edda", color: "#155724" },
    accuracyMedium: { backgroundColor: "#fff3cd", color: "#856404" },
    accuracyLow: { backgroundColor: "#f8d7da", color: "#721c24" },
    textComparison: { display: "flex", flexDirection: "column", gap: "12px" },
    comparisonLabel: { fontSize: "14px", fontWeight: "600", color: "#333333" },
    comparisonText: {
        padding: "12px 16px",
        border: "1px solid #e1e5e9",
        borderRadius: "8px",
        fontSize: "16px",
        direction: "rtl",
        textAlign: "right",
        backgroundColor: "#f8f9fa",
        color: "#333333",
    },
    expectedText: {
        display: "flex",
        flexWrap: "wrap",
        gap: "2px",
        fontSize: "18px",
        direction: "rtl",
        textAlign: "right",
        padding: "12px 16px",
        border: "1px solid #e1e5e9",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
    },
    characterCorrect: { backgroundColor: "#d4edda", color: "#155724", padding: "2px 4px", borderRadius: "4px" },
    characterIncorrect: { backgroundColor: "#f8d7da", color: "#721c24", padding: "2px 4px", borderRadius: "4px" },
    exerciseControls: {
        display: "flex",
        gap: "12px",
        flexWrap: "wrap",
        justifyContent: "center",
        paddingTop: "16px",
        borderTop: "1px solid #e1e5e9",
    },
    controlButton: {
        padding: "12px 20px",
        border: "2px solid #007bff",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
        color: "#007bff",
        fontSize: "14px",
        fontWeight: "600",
        cursor: "pointer",
        "&:hover": { backgroundColor: "#007bff", color: "#ffffff" },
    },
    primaryControlButton: { backgroundColor: "#007bff", color: "#ffffff", "&:hover": { backgroundColor: "#0056b3" } },

    "@media (max-width: 768px)": {
        exerciseControls: { flexDirection: "column" },
        controlButton: { width: "100%", justifyContent: "center" },
        expectedText: { fontSize: "16px" },
    },
});
