name: AKS - KEDA Setup

run-name: >
  AKS KEDA Setup | Environment: ${{
    inputs.environment_name || github.event.inputs.environment_name
  }} | GitHub Env: ${{ inputs.environment || github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (GitHub Environment)'
        required: true
        default: 'Development'
        type: choice
        options: [Development, Production]
      environment_name:
        description: 'Optional namespace/prefix (lowercase letters & digits). Empty -> dev'
        required: false
        default: ''
      use_keda:
        description: 'Enable KEDA for this environment'
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_name:
        required: false
        type: string
      skip_infra_steps:
        required: false
        type: boolean
        default: false
      use_chart:
        required: false
        type: boolean
        default: true

jobs:
  keda:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          AKS_RG="dev-zionet-learning-2025"
          AKS_NAME="aks-cluster-dev"
          az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing

      - name: Validate Kubernetes Namespace Exists
        # This step will fail the workflow if the namespace does not exist
        run: |
          if kubectl get ns ${{ inputs.environment_name }} >/dev/null 2>&1; then
            echo "Namespace '${{ inputs.environment_name }}' exists. Continuing."
          else
            echo "Error: Namespace '${{ inputs.environment_name }}' does not exist."
            exit 1
          fi

      - name: Deploy KEDA
        if: inputs.use_keda == true
        run: |
          cd devops/helm-tools
          chmod +x keda.sh
          ./keda.sh

  keda-deploy:
    needs: keda
    if: ${{ github.event.workflow == '.github/workflows/aks-keda.yaml' }}
    uses: ./.github/workflows/aks-helmcharts.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment || github.event.inputs.environment }}
      environment_name: ${{ inputs.environment_name || github.event.inputs.environment_name }}
      skip_infra_steps: false
      use_keda: ${{ fromJSON(github.event.inputs.use_keda || 'false') }}
    secrets: inherit
