output "postgres_fqdn" {
  value       = var.use_shared_postgres ? "" : azurerm_postgresql_flexible_server.this[0].fqdn
  description = "PostgreSQL server FQDN - NOTE: For private networking, actual FQDN is auto-generated by Azure"
}

# Output a note about the private networking FQDN issue
output "postgres_private_fqdn_note" {
  value = var.use_shared_postgres ? "" : "IMPORTANT: When using private networking, Azure auto-generates DNS records. Use: az network private-dns record-set a list --zone-name privatelink.postgres.database.azure.com --resource-group ${var.resource_group_name} to get the actual FQDN"
  description = "Instructions for getting the actual private FQDN"
}

output "postgres_admin_username" {
  value       = var.use_shared_postgres ? "" : azurerm_postgresql_flexible_server.this[0].administrator_login
  description = "Administrator username"
}

output "postgres_database_name" {
  value       = var.database_name
  description = "Database name"
}

output "postgres_connection_string" {
  value = var.use_shared_postgres ? "" : format("Host=%s;Database=%s;Username=%s;Password=%s;SslMode=Require", 
    # NOTE: This FQDN is for reference only. For private networking, Azure auto-generates DNS records
    # The actual FQDN must be retrieved using Azure CLI and updated in Key Vault manually or via CI/CD
    azurerm_postgresql_flexible_server.this[0].fqdn, 
    var.database_name, 
    azurerm_postgresql_flexible_server.this[0].administrator_login, 
    var.admin_password
  )
  description = "PostgreSQL connection string - NOTE: For private networking, FQDN must be updated with auto-generated value"
  sensitive   = true
}

output "id" {
  value = var.use_shared_postgres ? var.existing_server_id : azurerm_postgresql_flexible_server.this[0].id
  description = "The ID of the PostgreSQL flexible server"
}

output "private_dns_zone_id" {
  value       = var.use_shared_postgres ? null : azurerm_private_dns_zone.postgres[0].id
  description = "ID of the private DNS zone for PostgreSQL"
}

output "private_dns_zone_name" {
  value       = var.use_shared_postgres ? null : azurerm_private_dns_zone.postgres[0].name
  description = "Name of the private DNS zone for PostgreSQL"
}