import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  root: {
    display: "flex",
    gap: "2rem",
    alignItems: "stretch",
    padding: "1.5rem",
    background: "linear-gradient(135deg,#f7f9fc 0%, #eef2f7 100%)",
    height: "calc(100vh - 3rem)",
  },
  cardBase: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 2px 4px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)",
    borderRadius: 12,
    padding: "1.25rem 1.15rem 1.5rem",
    position: "relative",
    transition: "box-shadow .25s ease, transform .25s ease",
    "&:hover": {
      boxShadow: "0 4px 10px rgba(0,0,0,0.06), 0 6px 18px rgba(0,0,0,0.05)",
      transform: "translateY(-2px)",
    },
  },
  formContainer: {
    composes: "$cardBase",
    flex: "1 1 40%",
    maxWidth: 430,
    alignSelf: "center",
  },
  listContainer: {
    composes: "$cardBase",
    flex: "1 1 60%",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  tableArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "0.85rem",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    fontSize: 14,
    color: "#2d3748",
    fontWeight: 500,
    "& input": {
      marginTop: 4,
      padding: "0.55rem 0.7rem",
      border: "1px solid #cbd5e0",
      borderRadius: 8,
      fontSize: 14,
      color: "#1a202c",
      background: "#f8fafc",
      transition: "border-color .2s, box-shadow .2s, background .3s",
      "&:focus": {
        outline: "none",
        borderColor: "#6366f1",
        boxShadow: "0 0 0 3px rgba(99,102,241,0.25)",
        background: "#fff",
      },
      "&::placeholder": {
        color: "#94a3b8",
        opacity: 1,
      },
      "&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus":
        {
          WebkitBoxShadow: "0 0 0 1000px #f8fafc inset",
          boxShadow: "0 0 0 1000px #f8fafc inset",
          WebkitTextFillColor: "#1a202c",
          transition: "background-color 9999s ease-out, color 9999s ease-out",
          caretColor: "#1a202c",
        },
    },
  },
  // New separated table shell layout
  tableShell: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    background: "#fff",
    overflow: "hidden",
  },
  headerTable: {
    tableLayout: "fixed",
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    "& th": {
      background: "#f8fafc",
      fontWeight: 600,
      color: "#1f2937",
      borderBottom: "1px solid #e5e7eb",
    },
  },
  searchBar: {
    padding: "8px 12px 6px",
    borderBottom: "1px solid #e5e7eb",
    background: "#fff",
  },
  rowsScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    scrollbarGutter: "stable",
  },
  bodyTable: {
    tableLayout: "fixed",
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    "& td": {
      borderBottom: "1px solid #f1f5f9",
    },
  },

  error: {
    color: "#c00",
    fontSize: 11,
    marginTop: 2,
  },
  list: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "0.55rem",
    marginTop: "0.75rem",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  sectionTitle: {
    margin: "0 0 0.85rem",
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 0.3,
    color: "#1a202c",
    textAlign: "center",
  },
  submitButton: {
    marginTop: "0.4rem",
    background: "linear-gradient(90deg,#6366f1,#4f46e5)",
    color: "#ffffff !important",
    fontWeight: 600,
    border: "none",
    borderRadius: 10,
    padding: "0.65rem 1rem",
    fontSize: 14,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1.15,
    textShadow: "0 1px 2px rgba(0,0,0,0.25)",
    boxShadow: "0 2px 4px rgba(0,0,0,0.15)",
    transition: "background .25s, transform .2s, box-shadow .25s",
    "&:hover:not(:disabled)": {
      background: "linear-gradient(90deg,#4f46e5,#4338ca)",
    },
    "&:active:not(:disabled)": {
      transform: "translateY(1px)",
    },
    "&:disabled": {
      opacity: 0.6,
      cursor: "not-allowed",
    },
  },
  "@media (max-width: 920px)": {
    root: {
      flexDirection: "column",
      padding: "1rem",
    },
    formContainer: { maxWidth: "100%" },
    listContainer: { maxWidth: "100%" },
  },
  searchField: {
    "& .MuiOutlinedInput-root": {
      height: 32,
      borderRadius: 8,
      background: "#f8fafc",
    },
    "& .MuiOutlinedInput-input": {
      padding: "4px 8px",
      fontSize: 13,
      lineHeight: 1.2,
    },
    "& input:-webkit-autofill, & input:-webkit-autofill:hover, & input:-webkit-autofill:focus":
      {
        WebkitBoxShadow: "0 0 0 1000px #f8fafc inset",
        boxShadow: "0 0 0 1000px #f8fafc inset",
        WebkitTextFillColor: "#1f2937",
        caretColor: "#1f2937",
        transition: "background-color 9999s ease-out, color 9999s ease-out",
      },
  },
  paginationBar: {
    padding: "4px 12px",
    borderTop: "1px solid #e5e7eb",
    background: "#fff",
  },
});
